[discord.mydiscord]
# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# If you want roles/groups mentions to be shown with names instead of ID,
# you'll need to give your bot the "Manage Roles" permission.
Token="MY_DISCORD_API_KEY"
Server="687561274288373777" # picked from guilds the bot is connected to
RemoteNickFormat="[{PROTOCOL}] @{NICK} "


[slack]
[slack.myslack]
Token="MY_SLACK_API_KEY"
RemoteNickFormat="[{PROTOCOL}] @{NICK}"


[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="bridge"

[[gateway.inout]]
account="slack.myslack"
channel="bridge"