[general]
RemoteNickFormat="{NICK}"
TranslationAttribution=" [translated by :google:]"
PreserveThreading=true
ShowUserTyping=false
MediaDownloadSize=1000000
ShowJoinPart=false
NoSendJoinPart=false
# When someone is speaking from a platform without avatars, generate one from usernames
IconURL="https://github.com/identicons/{NICK}.png"

[slack]

[slack.hci]
Token="${SLACK_TOKEN}" # real user who may be a bot: matter 

## TELEGRAM EXAMPLE
# [telegram.hacklabto]
# Token="${TELEGRAM_TOKEN}" # bot user: hacklabto_bridgebot
# RemoteNickFormat="{NICK}@{PROTOCOL}: "
# UseInsecureURL=true

[discord.hci]
# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# If you want roles/groups mentions to be shown with names instead of ID,
# you'll need to give your bot the "Manage Roles" permission.
Token="${DISCORD_TOKEN}"
Server="${DISCORD_SERVER_ID}" # picked from guilds the bot is connected to
# RemoteNickFormat="[{PROTOCOL}] @{NICK} "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.hci"
channel="general"

[[gateway.inout]]
account="slack.hci"
channel="general"